### ISSUE TITLE
Cannot convert 'MainStore<AppState>' to expected 'MainStore<_>'

### ISSUE THREAD

**Issue by snown** [ReSwift/ReSwift-Router#5]
I'm having some trouble getting the Router instantiated. It seems to complain about my `mainStore` object regardless of if I'm using `MainStore` or `RecordingMainStore`, and I'm having trouble tracking down where it's choking.

Here's the error:
`Cannot convert value of type 'MainStore<AppState>' to expected argument type 'MainStore<_>'`

And here's the relevant `AppDelegate.swift` code:
```swift
import ReSwift
import ReSwiftRouter
import ReSwiftRecorder

var mainStore = MainStore(reducer: AppReducer(), state: AppState())
//var mainStore: RecordingMainStore<AppState> = RecordingMainStore(reducer: AppReducer(), appState: AppState())

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    
    var router: Router<AppState>!
    var window: UIWindow?

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        
        let initialController = UIStoryboard(name: "Main", bundle: nil).instantiateInitialViewController()
        
        router = Router(store: mainStore, rootRoutable: AppRoutable(root: initialController))
```

With the error presenting itself on that last line.

Thank you for the help.

**Comment by Ben-G** [comment]
@snown Have you tried specifying the generic type on both, the router and the store at the same time.
Here's an example of how I do it in the Counter Example App: https://github.com/ReSwift/CounterExample-Navigation-TimeTravel/blob/master/ReSwiftCounterExample/AppDelegate.swift#L14-L20

You could also download the app as a reference and compare your code to it.

Let me know if this helps!

**Comment by snown** [comment]
Thank you @Ben-G for getting back to me so quickly. I have tried that, and have been comparing to the Counter example app. In fact it seems that either the version I'm looking at either didn't have the generic type specified, or I removed it at some point, and it still compiles fine.

Long story short my mainStore declaration now looks like this:
```swift
var mainStore = MainStore<AppState>(reducer: AppReducer(), state: AppState())
```
and I'm getting the same error message.

Also in the code posted before, my commented out  `RecordingMainStore` declaration specified the generic in the var's type-annotation, unfortunately that didn't seem to make any difference either.

**Comment by Ben-G** [comment]
@snown Can you do me a quick favor and confirm that the Counter App is compiling correctly for you?

Also, have you used CocoaPods or Carthage to install dependencies? Just want to make sure I've published the latest library version on all platforms.

Thanks!

**Comment by snown** [comment]
Just downloaded the most current version of the Counter App. It compiles and runs fine with or without `<AppState>` in the mainStore declaration.

I installed ReSwift via CocoaPods, you can see the entry with version number from `Pod install` here:
```
Using ReSwift (0.2.3)
Installing ReSwiftRecorder (0.2.3)
Using ReSwiftRouter (0.2.3)
```

Let me know if I can do any more testing for you, or provide any more info.

**Comment by Ben-G** [comment]
@snown Seeing the `AppReducer` implementation as well would be nice. There might be a type mismatch there. Probably would be easiest if you could push this entire repo to GitHub :smile: 

The I could download and investigate.

I've just confirmed that the Counter Example also works with CocoaPods, so it actually must be an issue with your specific code.

**Comment by snown** [comment]
Ok, I went ahead and pushed a sanitized version to GitHub here: https://github.com/snown/ReSwift-Router-Issue

I verified I'm still seeing the same error.

Thanks.

**Comment by snown** [comment]
Any thoughts on what might be causing this issue? Or are you even able to reproduce it?

**Comment by Ben-G** [comment]
@snown You are next on my list; I'm currently pruning all the issues that accumulated over the last few days :smile:

**Comment by snown** [comment]
Great, no worries. Let me know if I can help in any way.

**Comment by Ben-G** [comment]
@snown Mistery solved, the underlying issue was that your `AppRoutable` could not be initialized, because it expects a `Routable` as argument, but received a `UIViewController`.

I just replaced the root routable with a dummy routable:

```
router = Router<AppState>(store: mainStore, rootRoutable: R())
```

And everything worked fine. So just a case of a very misleading compiler error message!

**Comment by snown** [comment]
Wow, weird indeed. Thanks for the help!

**Comment by Ben-G** [comment]
@snown You might also want to update to 0.2.4 right away. Brings some breaking API changes ;)
